# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Appointment',
        ),
    ]
